export const carBrands = [
 { value: "acura", label: "Acura" },
 { value: "alfa-romeo", label: "Alfa Romeo" },
 { value: "audi", label: "Audi" },
 { value: "bmw", label: "BMW" },
 { value: "buick", label: "Buick" },
 { value: "cadillac", label: "Cadillac" },
 { value: "chevrolet", label: "Chevrolet" },
 { value: "chrysler", label: "Chrysler" },
 { value: "dodge", label: "Dodge" },
 { value: "fiat", label: "Fiat" },
 { value: "ford", label: "Ford" },
 { value: "genesis", label: "Genesis" },
 { value: "gmc", label: "GMC" },
 { value: "honda", label: "Honda" },
 { value: "hyundai", label: "Hyundai" },
 { value: "infiniti", label: "Infiniti" },
 { value: "jaguar", label: "Jaguar" },
 { value: "jeep", label: "Jeep" },
 { value: "kia", label: "Kia" },
 { value: "land-rover", label: "Land Rover" },
 { value: "lexus", label: "Lexus" },
 { value: "lincoln", label: "Lincoln" },
 { value: "maserati", label: "Maserati" },
 { value: "mazda", label: "Mazda" },
 { value: "mercedes-benz", label: "Mercedes-Benz" },
 { value: "mini", label: "MINI" },
 { value: "mitsubishi", label: "Mitsubishi" },
 { value: "nissan", label: "Nissan" },
 { value: "porsche", label: "Porsche" },
 { value: "ram", label: "Ram" },
 { value: "subaru", label: "Subaru" },
 { value: "tesla", label: "Tesla" },
 { value: "toyota", label: "Toyota" },
 { value: "volkswagen", label: "Volkswagen" },
 { value: "volvo", label: "Volvo" },
];

export const carModels = {
 acura: [
  { value: "ilx", label: "ILX" },
  { value: "mdx", label: "MDX" },
  { value: "nsx", label: "NSX" },
  { value: "rdx", label: "RDX" },
  { value: "rlx", label: "RLX" },
  { value: "tlx", label: "TLX" },
 ],
 "alfa-romeo": [
  { value: "4c", label: "4C" },
  { value: "giulia", label: "Giulia" },
  { value: "stelvio", label: "Stelvio" },
 ],
 audi: [
  { value: "a3", label: "A3" },
  { value: "a4", label: "A4" },
  { value: "a5", label: "A5" },
  { value: "a6", label: "A6" },
  { value: "a7", label: "A7" },
  { value: "a8", label: "A8" },
  { value: "q3", label: "Q3" },
  { value: "q5", label: "Q5" },
  { value: "q7", label: "Q7" },
  { value: "q8", label: "Q8" },
  { value: "rs3", label: "RS3" },
  { value: "rs5", label: "RS5" },
  { value: "rs6", label: "RS6" },
  { value: "rs7", label: "RS7" },
  { value: "s3", label: "S3" },
  { value: "s4", label: "S4" },
  { value: "s5", label: "S5" },
  { value: "s6", label: "S6" },
  { value: "s7", label: "S7" },
  { value: "s8", label: "S8" },
  { value: "sq5", label: "SQ5" },
  { value: "sq7", label: "SQ7" },
  { value: "sq8", label: "SQ8" },
  { value: "tt", label: "TT" },
  { value: "tts", label: "TTS" },
 ],
 bmw: [
  { value: "2-series", label: "2 Series" },
  { value: "3-series", label: "3 Series" },
  { value: "4-series", label: "4 Series" },
  { value: "5-series", label: "5 Series" },
  { value: "6-series", label: "6 Series" },
  { value: "7-series", label: "7 Series" },
  { value: "8-series", label: "8 Series" },
  { value: "i3", label: "i3" },
  { value: "i8", label: "i8" },
  { value: "m2", label: "M2" },
  { value: "m3", label: "M3" },
  { value: "m4", label: "M4" },
  { value: "m5", label: "M5" },
  { value: "m6", label: "M6" },
  { value: "m8", label: "M8" },
  { value: "x1", label: "X1" },
  { value: "x2", label: "X2" },
  { value: "x3", label: "X3" },
  { value: "x4", label: "X4" },
  { value: "x5", label: "X5" },
  { value: "x6", label: "X6" },
  { value: "x7", label: "X7" },
 ],
 buick: [
  { value: "cascada", label: "Cascada" },
  { value: "encore", label: "Encore" },
  { value: "enclave", label: "Enclave" },
  { value: "envision", label: "Envision" },
  { value: "lacrosse", label: "LaCrosse" },
  { value: "regal", label: "Regal" },
  { value: "verano", label: "Verano" },
 ],
 cadillac: [
  { value: "ats", label: "ATS" },
  { value: "ct6", label: "CT6" },
  { value: "cts", label: "CTS" },
  { value: "escalade", label: "Escalade" },
  { value: "xt4", label: "XT4" },
  { value: "xt5", label: "XT5" },
  { value: "xt6", label: "XT6" },
 ],
 chevrolet: [
  { value: "blazer", label: "Blazer" },
  { value: "bolt", label: "Bolt" },
  { value: "camaro", label: "Camaro" },
  { value: "colorado", label: "Colorado" },
  { value: "corvette", label: "Corvette" },
  { value: "cruze", label: "Cruze" },
  { value: "equinox", label: "Equinox" },
  { value: "impala", label: "Impala" },
  { value: "malibu", label: "Malibu" },
  { value: "silverado", label: "Silverado" },
  { value: "spark", label: "Spark" },
  { value: "tahoe", label: "Tahoe" },
  { value: "traverse", label: "Traverse" },
  { value: "volt", label: "Volt" },
 ],
 chrysler: [
  { value: "300", label: "300" },
  { value: "aspen", label: "Aspen" },
  { value: "pacificia", label: "Pacifica" },
  { value: "voyager", label: "Voyager" },
 ],
 dodge: [
  { value: "charger", label: "Charger" },
  { value: "challenger", label: "Challenger" },
  { value: "durango", label: "Durango" },
  { value: "grand-caravan", label: "Grand Caravan" },
  { value: "journey", label: "Journey" },
 ],
 fiat: [
  { value: "124-spider", label: "124 Spider" },
  { value: "500", label: "500" },
  { value: "500l", label: "500L" },
  { value: "500x", label: "500X" },
 ],
 ford: [
  { value: "bronco", label: "Bronco" },
  { value: "edge", label: "Edge" },
  { value: "escape", label: "Escape" },
  { value: "explorer", label: "Explorer" },
  { value: "f-150", label: "F-150" },
  { value: "f-250", label: "F-250" },
  { value: "f-350", label: "F-350" },
  { value: "focus", label: "Focus" },
  { value: "fusion", label: "Fusion" },
  { value: "mustang", label: "Mustang" },
  { value: "ranger", label: "Ranger" },
  { value: "taurus", label: "Taurus" },
 ],
 genesis: [
  { value: "g70", label: "G70" },
  { value: "g80", label: "G80" },
  { value: "g90", label: "G90" },
 ],
 gmc: [
  { value: "acadia", label: "Acadia" },
  { value: "canyon", label: "Canyon" },
  { value: "sierra", label: "Sierra" },
  { value: "terrain", label: "Terrain" },
  { value: "yukon", label: "Yukon" },
 ],
 honda: [
  { value: "accord", label: "Accord" },
  { value: "civic", label: "Civic" },
  { value: "clarity", label: "Clarity" },
  { value: "cr-v", label: "CR-V" },
  { value: "hr-v", label: "HR-V" },
  { value: "insight", label: "Insight" },
  { value: "odyssey", label: "Odyssey" },
  { value: "passport", label: "Passport" },
  { value: "pilot", label: "Pilot" },
  { value: "ridgeline", label: "Ridgeline" },
 ],
 hyundai: [
  { value: "accent", label: "Accent" },
  { value: "elantra", label: "Elantra" },
  { value: "ioniq", label: "Ioniq" },
  { value: "kona", label: "Kona" },
  { value: "palisade", label: "Palisade" },
  { value: "santa-fe", label: "Santa Fe" },
  { value: "sonata", label: "Sonata" },
  { value: "tucson", label: "Tucson" },
  { value: "veloster", label: "Veloster" },
 ],
 infiniti: [
  { value: "q50", label: "Q50" },
  { value: "q60", label: "Q60" },
  { value: "q70", label: "Q70" },
  { value: "q80", label: "Q80" },
  { value: "qx30", label: "QX30" },
  { value: "qx50", label: "QX50" },
  { value: "qx60", label: "QX60" },
  { value: "qx70", label: "QX70" },
  { value: "qx80", label: "QX80" },
 ],
 jaguar: [
  { value: "e-pace", label: "E-PACE" },
  { value: "f-pace", label: "F-PACE" },
  { value: "f-type", label: "F-TYPE" },
  { value: "i-pace", label: "I-PACE" },
  { value: "xj", label: "XJ" },
  { value: "xe", label: "XE" },
  { value: "xf", label: "XF" },
 ],
 jeep: [
  { value: "compass", label: "Compass" },
  { value: "gladiator", label: "Gladiator" },
  { value: "grand-cherokee", label: "Grand Cherokee" },
  { value: "renegade", label: "Renegade" },
  { value: "wrangler", label: "Wrangler" },
 ],
 kia: [
  { value: "forte", label: "Forte" },
  { value: "k900", label: "K900" },
  { value: "niro", label: "Niro" },
  { value: "optima", label: "Optima" },
  { value: "rio", label: "Rio" },
  { value: "sorento", label: "Sorento" },
  { value: "soul", label: "Soul" },
  { value: "sportage", label: "Sportage" },
  { value: "stinger", label: "Stinger" },
  { value: "telluride", label: "Telluride" },
 ],
 "land-rover": [
  { value: "defender", label: "Defender" },
  { value: "discovery", label: "Discovery" },
  { value: "discovery-sport", label: "Discovery Sport" },
  { value: "evoque", label: "Evoque" },
  { value: "range-rover", label: "Range Rover" },
  { value: "range-rover-sport", label: "Range Rover Sport" },
  { value: "range-rover-velar", label: "Range Rover Velar" },
 ],
 lexus: [
  { value: "es", label: "ES" },
  { value: "gs", label: "GS" },
  { value: "gx", label: "GX" },
  { value: "is", label: "IS" },
  { value: "lc", label: "LC" },
  { value: "ls", label: "LS" },
  { value: "nx", label: "NX" },
  { value: "rc", label: "RC" },
  { value: "rx", label: "RX" },
 ],
 lincoln: [
  { value: "aviator", label: "Aviator" },
  { value: "continental", label: "Continental" },
  { value: "corsair", label: "Corsair" },
  { value: "mkc", label: "MKC" },
  { value: "mks", label: "MKS" },
  { value: "mkt", label: "MKT" },
  { value: "mkx", label: "MKX" },
  { value: "mkz", label: "MKZ" },
  { value: "navigator", label: "Navigator" },
  { value: "nautilus", label: "Nautilus" },
 ],
 maserati: [
  { value: "ghibli", label: "Ghibli" },
  { value: "granturismo", label: "GranTurismo" },
  { value: "levante", label: "Levante" },
  { value: "quattroporte", label: "Quattroporte" },
 ],
 mazda: [
  { value: "3", label: "3" },
  { value: "6", label: "6" },
  { value: "cx-3", label: "CX-3" },
  { value: "cx-5", label: "CX-5" },
  { value: "cx-9", label: "CX-9" },
  { value: "mx-5-miata", label: "MX-5 Miata" },
 ],
 "mercedes-benz": [
  { value: "amg-gt", label: "AMG GT" },
  { value: "cla", label: "CLA" },
  { value: "cls", label: "CLS" },
  { value: "e-class", label: "E-Class" },
  { value: "g-class", label: "G-Class" },
  { value: "glc", label: "GLC" },
  { value: "gle", label: "GLE" },
  { value: "glk", label: "GLK" },
  { value: "gls", label: "GLS" },
  { value: "gt", label: "GT" },
  { value: "s-class", label: "S-Class" },
  { value: "sl", label: "SL" },
  { value: "slc", label: "SLC" },
  { value: "sprinter", label: "Sprinter" },
 ],
 mini: [
  { value: "clubman", label: "Clubman" },
  { value: "convertible", label: "Convertible" },
  { value: "countryman", label: "Countryman" },
  { value: "hardtop", label: "Hardtop" },
  { value: "paceman", label: "Paceman" },
 ],
 mitsubishi: [
  { value: "eclipse-cross", label: "Eclipse Cross" },
  { value: "mirage", label: "Mirage" },
  { value: "outlander", label: "Outlander" },
  { value: "outlander-sport", label: "Outlander Sport" },
 ],
 nissan: [
  { value: "370z", label: "370Z" },
  { value: "altima", label: "Altima" },
  { value: "armada", label: "Armada" },
  { value: "frontier", label: "Frontier" },
  { value: "gt-r", label: "GT-R" },
  { value: "juke", label: "Juke" },
  { value: "kicks", label: "Kicks" },
  { value: "leaf", label: "Leaf" },
  { value: "maxima", label: "Maxima" },
  { value: "murano", label: "Murano" },
  { value: "nv", label: "NV" },
  { value: "pathfinder", label: "Pathfinder" },
  { value: "rogue", label: "Rogue" },
  { value: "rogue-sport", label: "Rogue Sport" },
  { value: "sentra", label: "Sentra" },
  { value: "titan", label: "Titan" },
  { value: "versa", label: "Versa" },
 ],
 porsche: [
  { value: "718", label: "718" },
  { value: "911", label: "911" },
  { value: "boxster", label: "Boxster" },
  { value: "cayenne", label: "Cayenne" },
  { value: "cayman", label: "Cayman" },
  { value: "macan", label: "Macan" },
  { value: "panamera", label: "Panamera" },
 ],
 ram: [
  { value: "1500", label: "1500" },
  { value: "2500", label: "2500" },
  { value: "3500", label: "3500" },
  { value: "pro-master", label: "ProMaster" },
 ],
 subaru: [
  { value: "ascent", label: "Ascent" },
  { value: "brz", label: "BRZ" },
  { value: "crosstrek", label: "Crosstrek" },
  { value: "forester", label: "Forester" },
  { value: "impreza", label: "Impreza" },
  { value: "legacy", label: "Legacy" },
  { value: "outback", label: "Outback" },
  { value: "wrx", label: "WRX" },
  { value: "wrx-sti", label: "WRX STI" },
  { value: "xt", label: "XT" },
 ],
 tesla: [
  { value: "model-3", label: "Model 3" },
  { value: "model-s", label: "Model S" },
  { value: "model-x", label: "Model X" },
  { value: "model-y", label: "Model Y" },
  { value: "roadster", label: "Roadster" },
 ],
 toyota: [
  { value: "4runner", label: "4Runner" },
  { value: "86", label: "86" },
  { value: "avalon", label: "Avalon" },
  { value: "camry", label: "Camry" },
  { value: "corolla", label: "Corolla" },
  { value: "highlander", label: "Highlander" },
  { value: "land-cruiser", label: "Land Cruiser" },
  { value: "mirai", label: "Mirai" },
  { value: "prius", label: "Prius" },
  { value: "rav4", label: "RAV4" },
  { value: "sequoia", label: "Sequoia" },
  { value: "sienna", label: "Sienna" },
  { value: "supra", label: "Supra" },
  { value: "tacoma", label: "Tacoma" },
  { value: "tundra", label: "Tundra" },
 ],
 volkswagen: [
  { value: "arteon", label: "Arteon" },
  { value: "atlas", label: "Atlas" },
  { value: "beetle", label: "Beetle" },
  { value: "cc", label: "CC" },
  { value: "e-golf", label: "e-Golf" },
  { value: "golf", label: "Golf" },
  { value: "golf-alltrack", label: "Golf Alltrack" },
  { value: "golf-r", label: "Golf R" },
  { value: "golf-sportwagen", label: "Golf SportWagen" },
  { value: "id-4", label: "ID.4" },
  { value: "jetta", label: "Jetta" },
  { value: "passat", label: "Passat" },
  { value: "tiguan", label: "Tiguan" },
 ],
 volvo: [
  { value: "s60", label: "S60" },
  { value: "s90", label: "S90" },
  { value: "v60", label: "V60" },
  { value: "v90", label: "V90" },
  { value: "xc40", label: "XC40" },
  { value: "xc60", label: "XC60" },
  { value: "xc90", label: "XC90" },
 ],
};
