export const colorsList = [
 { value: "black", label: "Black" },
 { value: "white", label: "White" },
 { value: "red", label: "Red" },
 { value: "orange", label: "Orange" },
 { value: "yellow", label: "Yellow" },
 { value: "green", label: "Green" },
 { value: "blue", label: "Blue" },
 { value: "indigo", label: "Indigo" },
 { value: "violet", label: "Violet" },
 { value: "pink", label: "Pink" },
 { value: "brown", label: "Brown" },
 { value: "gray", label: "Gray" },
 { value: "silver", label: "Silver" },
 { value: "gold", label: "Gold" },
 { value: "beige", label: "Beige" },
 { value: "turquoise", label: "Turquoise" },
 { value: "lavender", label: "Lavender" },
 { value: "teal", label: "Teal" },
 { value: "tan", label: "Tan" },
 { value: "olive", label: "Olive" },
 { value: "navy", label: "Navy" },
 { value: "maroon", label: "Maroon" },
];
